name: Android CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0
      - name: Set ANDROID_SDK_ROOT
        run: echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew test
